name: Pruebas unitarias

on:
  push:
    branches: [ master ]

jobs:
  job1:
    name: Pruebas
    runs-on: ubuntu-latest
    outputs:
      salida: ${{ steps.imprimir.outputs.respuesta }}
    
    steps:
    - name: Checkout de repositorio
      uses: actions/checkout@v4
      
    - name: Configuración de entorno de python
      uses: actions/setup-python@v5
      with:
          python-version: '3.11'
          
    - name: Instalación de librerías y dependencias
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install coverage
        
    - name: Correr pruebas
      id: correr-pruebas
      env:
        PYTHONPATH: src
      run: python -m unittest -v tests/test-persona.py
      
    - name: Validar resultado con errores
      if: ${{ failure() }}
      env:
        MENSAJE_ERROR: Una o varias pruebas fallaron
      run: echo "respuesta=${MENSAJE_ERROR}" >> $GITHUB_OUTPUT
      
    - name: Validar resultado sin errores
      if: ${{ success() }}
      env:
        MENSAJE_EXITO: Todas las pruebas fueron exitosas
      run: echo "respuesta=${MENSAJE_EXITO}" >> $GITHUB_OUTPUT
      
    - name: Cálculo de cubrimiento
      id: cubrimiento
      if: ${{ success() }}
      env:
        PYTHONPATH: src
      run: |
          coverage run -m unittest tests/test-persona.py
          coverage report -m