name: Pruebas unitarias
on:
  push:
    branches: [ master ]
jobs:
  job1:
    name: Pruebas
    runs-on: ubuntu-latest
    steps:
    - name: Checkout de repositorio
      uses: actions/checkout@v2
    - name: Configuración de entorno de python
      uses: actions/setup-python@v2
      with:
          python-version: '3.11'
    - name: Instalación de librerías y dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Correr pruebas
      env:
        PYTHONPATH: src
      run: python -m unittest -v tests/test-persona.py

    - name: Cálculo de cubrimiento
      env:
        PYTHONPATH: src
      run: |
        coverage run --source=src/tutorial_actions -m unittest tests/test-persona.py
        coverage report -m
