name: Pruebas unitarias

on:
  push:
    branches: [ master ]

jobs:
  job1:
    name: Pruebas
    runs-on: ubuntu-latest

    steps:
      - name: Checkout de repositorio
        uses: actions/checkout@v4

      - name: Configuración de entorno de python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalación de librerías y dependencias
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install coverage

      - name: Cálculo de cubrimiento (tests bajo coverage)
        env:
          PYTHONPATH: src
        run: |
          coverage run --source=src/tutorial_actions -m unittest discover -s tests -p "test-*.py" -v
          coverage report -m